defaults: &defaults
  working_directory: ~/circleci-test-tags
  environment:
    SERVICE_NAME: circleci-test-tags
    DOCKER_REPO: stefanwalther/circleci-test-tags
    DOCKER_URL: https://download.docker.com/linux/static/edge/x86_64/docker-18.09.6.tgz
    DOCKER_COMPOSE_URL: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64

version: 2.1

jobs:
  build:
    <<: *defaults
    machine: true

    steps:
      - checkout
#      - run:
#          name: Upgrade Docker
#          command: |
#            set -e
#            curl -sSL $DOCKER_URL | sudo tar -xz --strip-components=1 -C /usr/bin/
#            sudo service docker restart
#      - run:
#          name: Pull public docker images in the background
#          background: true
#          command: |
#            docker pull busybox
#      - run:
#          name: Upgrade Docker Compose
#          command: |
#            set -e
#            loc=$(which docker-compose)
#            sudo curl -sSLf -z $loc -o $loc $DOCKER_COMPOSE_URL
#            sudo chmod 755 $loc
      - run:
          name: Update version
          command: |
            set -e
            VER=$(node -e "console.log(require('./package.json').version.replace(/-[0-9]+/, '-$CIRCLE_BUILD_NUM'))")
            echo "Version is: $VER"
            echo "$VER" > ./version.txt
            if (echo $VER | egrep -- '-[0-9]+$' 1> /dev/null); then
              npm version $VER --no-git-tag-version
            fi
      - persist_to_workspace:
          root: ~/circleci-test-tags
          paths:
            - version.txt

      - run:
          name: Build image
          command: make build
#      - add_ssh_keys
#      - deploy:
#          name: Push image(s) to Docker Hub
#          command: |
#            PKG_VER=$(cat ./version.txt)
#            BUILD_NR="${CIRCLE_BUILD_NUM}"
#
#            # Always push the build-nr
#            docker tag $DOCKER_REPO $DOCKER_REPO:$PKG_VER.$BUILD_NR
#
#            # Only branch "master" is being pushed to Docker Hub
#            if [ "${CIRCLE_BRANCH}" == "master" ]; then
#              if [ ! -z "$CIRCLE_TAG" ]; then
#                docker tag $DOCKER_REPO $DOCKER_REPO:$CIRCLE_TAG
#              fi
#              docker tag $DOCKER_REPO "${DOCKER_REPO}:${PKG_VER}"
#              docker tag $DOCKER_REPO $DOCKER_REPO:latest
#            fi
#            docker push $DOCKER_REPO


  push_any:
    <<: *defaults
    machine: true
    steps:
      - attach_workspace:
            at: ~/circleci-test-tags
      - run:
          name: Log in to DockerHub
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
      - run:
          name: Test
          command: |
            PKG_VER=$(cat ~/circleci-test-tags/version.txt)
            echo "We are working with version $PKG_VER"
      - run:
          name: Push image(s) to Docker Hub
          command: |
            echo "Pushing image using PKG_VER: $PKG_VER"
            BUILD_NR="${CIRCLE_BUILD_NUM}"

            # Always push the build-nr
            docker tag $DOCKER_REPO $DOCKER_REPO:$PKG_VER.$BUILD_NR

            # Only branch "master" is being pushed to Docker Hub
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              if [ ! -z "$CIRCLE_TAG" ]; then
                docker tag $DOCKER_REPO $DOCKER_REPO:$CIRCLE_TAG
              fi
              #docker tag $DOCKER_REPO "${DOCKER_REPO}:${PKG_VER}"
              docker tag $DOCKER_REPO $DOCKER_REPO:latest
            fi
            docker push $DOCKER_REPO


workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - push_any:
          requires:
            - build
