defaults: &defaults
  working_directory: ~/circleci-test-tags
  environment:
    SERVICE_NAME: circleci-test-tags
    DOCKER_REPO: stefanwalther/circleci-test-tags
    DOCKER_URL: https://download.docker.com/linux/static/edge/x86_64/docker-18.09.6.tgz
    DOCKER_COMPOSE_URL: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
  machine:
    docker_layer_caching: true

version: 2.1

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
#      - run:
#          name: Pull public docker images in the background
#          background: true
#          command: |
#            docker pull busybox
      - run:
          name: Update version
          command: |
            set -e
            VER=$(node -e "console.log(require('./package.json').version.replace(/-[0-9]+/, '-$CIRCLE_BUILD_NUM'))")
            echo "Version is: $VER"
            echo "$VER" > ./version.txt
            if (echo $VER | egrep -- '-[0-9]+$' 1> /dev/null); then
              npm version $VER --no-git-tag-version
            fi
      - persist_to_workspace:
          root: ~/circleci-test-tags
          paths:
            - version.txt
      - run:
          name: Build image
          command: make build
      - run:
          name: Save Docker image
          command: |
            docker save -o ~/circleci-test-tags/circleci-test-tags.tar "$DOCKER_REPO"
      - persist_to_workspace:
          root: ~/circleci-test-tags
          paths:
            - circleci-test-tags.tar


  push_tags_only:
    <<: *defaults
    steps:
      - attach_workspace:
            at: ~/circleci-test-tags
      - run:
          name: Load Docker image
          command: |
            docker load -i ~/circleci-test-tags/circleci-test-tags.tar
      - run:
          name: Log in to DockerHub
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
      - run:
          name: Test
          command: |
            PKG_VER=$(cat ~/circleci-test-tags/version.txt)
            echo "We are working with version $PKG_VER"
      - run:
          name: Push image(s) to Docker Hub
          command: |
            PKG_VER=$(cat ~/circleci-test-tags/version.txt)
            echo "Pushing image using PKG_VER: $PKG_VER"
            BUILD_NR="${CIRCLE_BUILD_NUM}"

            echo "We have BUILD_NR: $BUILD_NR"

            # Always push the build-nr
            docker tag $DOCKER_REPO $DOCKER_REPO:$PKG_VER.$BUILD_NR

            # Only branch "master" is being pushed to Docker Hub
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              if [ ! -z "$CIRCLE_TAG" ]; then
                docker tag $DOCKER_REPO $DOCKER_REPO:$CIRCLE_TAG
              fi
              #docker tag $DOCKER_REPO "${DOCKER_REPO}:${PKG_VER}"
              docker tag $DOCKER_REPO $DOCKER_REPO:latest
            fi
            docker push $DOCKER_REPO

  push_any:
    <<: *defaults
    steps:
      - attach_workspace:
            at: ~/circleci-test-tags
      - run:
          name: Load Docker image
          command: |
            docker load -i ~/circleci-test-tags/circleci-test-tags.tar
      - run:
          name: Log in to DockerHub
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
      - run:
          name: Test
          command: |
            PKG_VER=$(cat ~/circleci-test-tags/version.txt)
            echo "We are working with version $PKG_VER"
      - run:
          name: Push image(s) to Docker Hub
          command: |
            PKG_VER=$(cat ~/circleci-test-tags/version.txt)
            echo "Pushing image using PKG_VER: $PKG_VER"
            BUILD_NR="${CIRCLE_BUILD_NUM}"

            echo "We have BUILD_NR: $BUILD_NR"

            # Always push the build-nr
            docker tag $DOCKER_REPO $DOCKER_REPO:$PKG_VER.$BUILD_NR

            # Only branch "master" is being pushed to Docker Hub
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              if [ ! -z "$CIRCLE_TAG" ]; then
                docker tag $DOCKER_REPO $DOCKER_REPO:$CIRCLE_TAG
              fi
              #docker tag $DOCKER_REPO "${DOCKER_REPO}:${PKG_VER}"
              docker tag $DOCKER_REPO $DOCKER_REPO:latest
            fi
            docker push $DOCKER_REPO



workflows:
  version: 2

  workflow:
    jobs:
      - build
      - push_any:
          requires:
            - build
      - push_tags_only:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
